In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
df = pd.read_csv('data/Final_data.csv')
df.head()

,Unnamed: 0,week_of_outbreak,state_ut,district,Disease,Cases,Deaths,day,mon,year,Latitude,Longitude,preci,LAI,Temp
0,0,1st week,Meghalaya,East Jaintia Hills,Acute Diarrhoeal Disease,160,NaN,2,1,2022,25.251576,92.484050,0.020354,34.5,291.533333
1,1,2nd week,Maharashtra,Gadchiroli,Malaria,7,2.0,10,1,2022,19.759070,80.162281,0.007479,9.0,299.970000
2,2,3rd week,Tamil Nadu,Pudukottai,Acute Diarrhoeal Disease,8,NaN,18,1,2022,10.382651,78.819126,0.107413,12.0,300.766667
3,3,3rd week,Gujarat,Patan,Acute Diarrhoeal Disease,7,NaN,11,1,2022,23.774057,71.683735,0.065094,9.0,299.080000
4,4,3rd week,Kerala,Ernakulam,Acute Diarrhoeal Disease,14,NaN,24,12,2021,9.984080,76.274146,0.041256,33.0,303.028000

In [4]:
# Filter for North East states only
north_east_states = [
    'Arunachal Pradesh', 'Assam', 'Manipur', 'Meghalaya',
    'Mizoram', 'Nagaland', 'Tripura', 'Sikkim'
]
df_ne = df[df['state_ut'].isin(north_east_states)]
df_ne

,Unnamed: 0,week_of_outbreak,state_ut,district,Disease,Cases,Deaths,day,mon,year,Latitude,Longitude,preci,LAI,Temp
0,0,1st week,Meghalaya,East Jaintia Hills,Acute Diarrhoeal Disease,160,NaN,2,1,2022,25.251576,92.484050,0.020354,34.5,291.533333
100,100,20th week,Assam,Udalguri,Acute Diarrhoeal Disease,14,NaN,17,5,2022,26.772532,92.106417,2.407587,NaN,300.920000
109,109,20th week,Meghalaya,West Jaintia Hills,Acute Diarrhoeal Disease,110,NaN,12,5,2022,25.442597,92.298827,1.120595,17.0,302.013333
110,110,20th week,Meghalaya,West Jaintia Hills,Acute Diarrhoeal Disease,60,NaN,1,5,2022,25.442597,92.298827,0.720570,NaN,300.456000
111,111,21st week,Arunachal Pradesh,West Kameng,Acute Diarrhoeal Disease,37,NaN,27,5,2022,27.400000,92.350000,1.087378,18.0,291.860000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8922,8922,44th week,Assam,Barpeta,Cholera,1010,13.0,28,9,2009,26.341422,91.016743,0.597549,19.0,300.992000
8947,8947,47th week,Assam,Sonitpur,Acute Diarrhoeal Disease,65,1.0,13,11,2009,26.767771,92.701409,0.004614,31.0,299.900000
8965,8965,50th week,Arunachal Pradesh,Tirap,Malaria,115,0.0,1,12,2009,27.030169,95.497918,0.066968,50.0,289.630000
8974,8974,51st week,Assam,Sonitpur,Malaria,578,8.0,28,9,2009,26.767771,92.701409,0.600370,32.0,294.745000
8976,8976,51st week,Arunachal Pradesh,Tirap,Malaria,292,0.0,1,12,2009,27.030169,95.497918,0.066968,50.0,289.630000

In [ ]:
df_ne.to_csv('data/Final_data_NE.csv')